tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "ack"
brew "dockutil"
brew "arping"
brew "python"
brew "awscli"
brew "bwm-ng"
brew "cmake"
brew "fortune"
brew "fzf"
brew "git"
brew "graphviz"
brew "ipcalc"
brew "iperf"
brew "jq"
brew "mas"
brew "nmap"
brew "node"
brew "pwgen"
brew "python@2"
brew "ruby"
brew "terraform"
brew "terragrunt"
brew "tree"
brew "vim"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "adobe-acrobat-reader"
cask "atom"
cask "caffeine"
cask "firefox"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iterm2"
cask "keyboardcleantool"
cask "mactex"
cask "omnigraffle"
cask "onedrive"
cask "postman"
cask "private-internet-access"
cask "sketchup"
cask "skype"
cask "spotify"
cask "sublime-text"
cask "texmaker"
cask "texstudio"
cask "textmate"
cask "tigervnc-viewer"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "vmware-horizon-client"
cask "webex-teams"
cask "wireshark"
mas "ELAN Viewer", id: 1083657906
mas "Microsoft Remote Desktop", id: 1295203466
mas "Monity", id: 915542151
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "WiFi Explorer", id: 494803304
mas "Wunderlist", id: 410628904