tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iterm2"
brew "ack"
brew "watch"
brew "ansible"
brew "arping"
brew "awscli"
brew "bash-completion"
brew "bwm-ng"
brew "cmake"
brew "dockutil"
brew "fortune"
brew "fzf"
brew "git"
brew "graphviz"
brew "ipcalc"
brew "iperf"
brew "jq"
brew "mas"
brew "ncftp"
brew "nmap"
brew "pwgen"
brew "pyenv"
brew "python@2"
brew "ssh-copy-id"
brew "terraform"
brew "terraform-inventory"
brew "terraform-provisioner-ansible"
brew "terragrunt"
brew "tree"
brew "vim"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "atom"
cask "firefox"
cask "keyboardcleantool"
cask "mactex"
cask "macvim"
cask "microsoft-office"
cask "omnigraffle"
cask "postman"
cask "private-internet-access"
cask "slack"
cask "textmate"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "vmware-fusion"
cask "vmware-horizon-client"
cask "webex-teams"
cask "wireshark"
cask "transmit"
mas "ELAN Viewer", id: 1083657906
#mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Monity", id: 915542151
#mas "Numbers", id: 409203825
#mas "Pages", id: 409201541
mas "WiFi Explorer", id: 494803304
