# Mac setup playbook
---
- hosts: localhost
  connection: local

  vars_files:
    - vars.yml

  tasks:

    - name: Dock configuration
      include: dock.yml

    - name: Get current Terminal profile.
      shell: defaults read com.apple.Terminal 'Default Window Settings'
      register: terminal_theme
      changed_when: false

#    - name: Ensure custom Terminal profile is added.
#      shell: open files/Solarized-Dark.terminal
#      changed_when: false
#      when: "'Solarized-Dark' not in terminal_theme.stdout"
#
#    - name: Ensure custom Terminal profile is set as default.
#      shell: "{{ item }}"
#      with_items:
#        - defaults write com.apple.Terminal 'Default Window Settings' -string 'Solarized-Dark'
#        - defaults write com.apple.Terminal 'Startup Window Settings' -string 'Solarized-Dark'
#      changed_when: false
#      when: "'Solarized Dark ansi' not in terminal_theme.stdout"
#
    - name: Show clock during screensaver
      osx_defaults:
        domain: com.apple.screensaver
        host: currentHost
        key: showClock
        type: int
        value: 1
        
    - name: Change save dialog
      osx_defaults:
        domain: NSGlobalDomain
        host: currentHost
        key: NSNavPanelExpandedStateForSaveMode
        type: bool
        value:  true
    
    - name: Change save dialog 2
      osx_defaults:
        domain: NSGlobalDomain
        host: currentHost
        key: NSNavPanelExpandedStateForSaveMode2
        type: bool
        value:  true
        
    - name: Always show scoll bars
      osx_defaults:
        domain: NSGlobalDomain
        host: currentHost
        key: AppleShowScrollBars
        type: string
        value:  "Always"
    
    - name: Remove timestamp from screenshots
      osx_defaults:
        domain: com.apple.screencapture
        host: currentHost
        key:  include-date
        value:  0
        
    - name: Expand print dialog
      osx_defaults:
        domain: NSGlobalDomain
        host: currentHost
        key: PMPrintingExpandedStateForPrint
        value: true

    - name: Expand print dialog
      osx_defaults:
        domain: NSGlobalDomain
        host: currentHost
        key: PMPrintingExpandedStateForPrint2
        value: true
        
    - name: Disable the “Are you sure you want to open this application?” dialog
      osx_defaults:
        domain: com.apple.LaunchServices
        host: currentHost
        key: LSQuarantine
        value: false
        
    - name: Trackpad enable tap to click for this user and for the login screen
      osx_defaults:
        domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
        host: currentHost
        key: Clicking
        value: true
        
    
