# Mac setup playbook
---
- hosts: localhost
  connection: local

  vars_files:
    - vars.yml

  tasks:

    - name: Dock configuration
      include: dock.yml

    - name: Get current Terminal profile.
      shell: defaults read com.apple.Terminal 'Default Window Settings'
      register: terminal_theme
      changed_when: false

#    - name: Ensure custom Terminal profile is added.
#      shell: open files/Solarized-Dark.terminal
#      changed_when: false
#      when: "'Solarized-Dark' not in terminal_theme.stdout"
#
#    - name: Ensure custom Terminal profile is set as default.
#      shell: "{{ item }}"
#      with_items:
#        - defaults write com.apple.Terminal 'Default Window Settings' -string 'Solarized-Dark'
#        - defaults write com.apple.Terminal 'Startup Window Settings' -string 'Solarized-Dark'
#      changed_when: false
#      when: "'Solarized Dark ansi' not in terminal_theme.stdout"
#
    - name: Show clock during screensaver
      osx_defaults:
        domain: com.apple.screensaver
        host: currentHost
        key: showClock
        type: int
        value: 1
        
    - name: Change save dialog
      osx_defaults:
        domain: NSGlobalDomain
        host: currentHost
        key: NSNavPanelExpandedStateForSaveMode
        type: bool
        value:  true
    
    - name: Change save dialog 2
      osx_defaults:
        domain: NSGlobalDomain
        host: currentHost
        key: NSNavPanelExpandedStateForSaveMode2
        type: bool
        value:  true
        
    - name: Always show scoll bars
      osx_defaults:
        domain: NSGlobalDomain
        host: currentHost
        key: AppleShowScrollBars
        type: string
        value:  "Always"
    
    - name: Remove timestamp from screenshots
      osx_defaults:
        domain: com.apple.screencapture
        host: currentHost
        key:  include-date
        value:  0
        
    - name: Expand print dialog
      osx_defaults:
        domain: NSGlobalDomain
        host: currentHost
        key: PMPrintingExpandedStateForPrint
        value: true

    - name: Expand print dialog
      osx_defaults:
        domain: NSGlobalDomain
        host: currentHost
        key: PMPrintingExpandedStateForPrint2
        value: true
        
    - name: Disable the “Are you sure you want to open this application?” dialog
      osx_defaults:
        domain: com.apple.LaunchServices
        host: currentHost
        key: LSQuarantine
        value: false

#    # Trackpad: enable tap to click for this user and for the login screen
#    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
#    defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
#    defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
#
#    # Trackpad: map bottom right corner to right-click
#    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
#    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
#    defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
#    defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true
    
#  # Use scroll gesture with the Ctrl (^) modifier key to zoom
#  defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
#  defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144
#  # Follow the keyboard focus while zoomed in
#  defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

#  # Save screenshots to the desktop
#  defaults write com.apple.screencapture location -string "${HOME}/Desktop"
#  
#  # Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
#  defaults write com.apple.screencapture type -string "png"
#  
#  # Disable shadow in screenshots
#  defaults write com.apple.screencapture disable-shadow -bool true

#  # Set Desktop as the default location for new Finder windows
#  # For other paths, use `PfLo` and `file:///full/path/here/`
#  defaults write com.apple.finder NewWindowTarget -string "PfDe"
#  defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"

#  # Finder: show status bar
#  defaults write com.apple.finder ShowStatusBar -bool true
#  
#  # Finder: show path bar
#  defaults write com.apple.finder ShowPathbar -bool true
#  
#  # Display full POSIX path as Finder window title
#  defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
#  
#  # Keep folders on top when sorting by name
#  defaults write com.apple.finder _FXSortFoldersFirst -bool true
#  
#  # When performing a search, search the current folder by default
#  defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
#  
#  # Disable the warning when changing a file extension
#  defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
#  
#  # Enable spring loading for directories
#  defaults write NSGlobalDomain com.apple.springing.enabled -bool true
#  
#  # Remove the spring loading delay for directories
#  defaults write NSGlobalDomain com.apple.springing.delay -float 0
#  
#  # Avoid creating .DS_Store files on network or USB volumes
#  defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
#  defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
#  
#  # Disable disk image verification
#  defaults write com.apple.frameworks.diskimages skip-verify -bool true
#  defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
#  defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true
#  
#  # Automatically open a new Finder window when a volume is mounted
#  defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
#  defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
#  defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true
#  

# Set the icon size of Dock items to 36 pixels
# defaults write com.apple.dock tilesize -int 36

# Minimize windows into their application’s icon
# defaults write com.apple.dock minimize-to-application -bool true

# Show indicator lights for open applications in the Dock
#  defaults write com.apple.dock show-process-indicators -bool true
